import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>React project template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen p-4 flex flex-1 flex-col justify-center items-center">
        <h1 className="text-center">Welcome to React project template</h1>
      </main>

      <footer className="flex flex-1 justify-center p-4 bg-gray-100 border-t border-gray-300">
        <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">
          <span>Powered by</span>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </a>
      </footer>
    </>
  );
};

export default Home;
